set_property PACKAGE_PIN B16 [get_ports sck]
set_property PACKAGE_PIN B17 [get_ports miso]
set_property PACKAGE_PIN A16 [get_ports reset_oled]
set_property PACKAGE_PIN A14 [get_ports dc]
set_property PACKAGE_PIN P17 [get_ports clk]
set_property PACKAGE_PIN A15 [get_ports sck_reg]
set_property PACKAGE_PIN A18 [get_ports rxd]

set_property PACKAGE_PIN R1 [get_ports keepgoing]
set_property IOSTANDARD LVCMOS33 [get_ports keepgoing]
set_property PACKAGE_PIN G4 [get_ports showdelay]
set_property IOSTANDARD LVCMOS33 [get_ports showdelay]
set_property PACKAGE_PIN N4 [get_ports addr_reset]
set_property IOSTANDARD LVCMOS33 [get_ports addr_reset]

set_property IOSTANDARD LVCMOS33 [get_ports sck]
set_property IOSTANDARD LVCMOS33 [get_ports miso]
set_property IOSTANDARD LVCMOS33 [get_ports reset_oled]
set_property IOSTANDARD LVCMOS33 [get_ports dc]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports sck_reg]
set_property IOSTANDARD LVCMOS33 [get_ports rxd]



create_pblock {pblock_cur_st[3]_i_4}
resize_pblock [get_pblocks {pblock_cur_st[3]_i_4}] -add {SLICE_X48Y60:SLICE_X51Y65}
create_pblock pblock_oled_clear
add_cells_to_pblock [get_pblocks pblock_oled_clear] [get_cells -quiet [list oled_clear]]
resize_pblock [get_pblocks pblock_oled_clear] -add {SLICE_X34Y147:SLICE_X47Y148}


set_property PACKAGE_PIN K2 [get_ports st_init]
set_property PACKAGE_PIN J2 [get_ports st_clear]
set_property PACKAGE_PIN J3 [get_ports st_wait]
set_property PACKAGE_PIN H4 [get_ports st_write]
set_property IOSTANDARD LVCMOS33 [get_ports st_init]
set_property IOSTANDARD LVCMOS33 [get_ports st_clear]
set_property IOSTANDARD LVCMOS33 [get_ports st_wait]
set_property IOSTANDARD LVCMOS33 [get_ports st_write]
set_property PACKAGE_PIN D4 [get_ports {sseg0[0]}]
set_property PACKAGE_PIN E3 [get_ports {sseg0[1]}]
set_property PACKAGE_PIN D3 [get_ports {sseg0[2]}]
set_property PACKAGE_PIN F4 [get_ports {sseg0[3]}]
set_property PACKAGE_PIN F3 [get_ports {sseg0[4]}]
set_property PACKAGE_PIN E2 [get_ports {sseg0[5]}]
set_property PACKAGE_PIN D2 [get_ports {sseg0[6]}]
set_property PACKAGE_PIN H2 [get_ports {sseg0[7]}]
set_property PACKAGE_PIN B4 [get_ports {sseg1[0]}]
set_property PACKAGE_PIN A4 [get_ports {sseg1[1]}]
set_property PACKAGE_PIN A3 [get_ports {sseg1[2]}]
set_property PACKAGE_PIN B1 [get_ports {sseg1[3]}]
set_property PACKAGE_PIN A1 [get_ports {sseg1[4]}]
set_property PACKAGE_PIN B3 [get_ports {sseg1[5]}]
set_property PACKAGE_PIN B2 [get_ports {sseg1[6]}]
set_property PACKAGE_PIN D5 [get_ports {sseg1[7]}]
set_property PACKAGE_PIN G6 [get_ports {en0[0]}]
set_property PACKAGE_PIN E1 [get_ports {en0[1]}]
set_property PACKAGE_PIN F1 [get_ports {en0[2]}]
set_property PACKAGE_PIN G1 [get_ports {en0[3]}]
set_property PACKAGE_PIN H1 [get_ports {en1[0]}]
set_property PACKAGE_PIN C1 [get_ports {en1[1]}]
set_property PACKAGE_PIN C2 [get_ports {en1[2]}]
set_property PACKAGE_PIN G2 [get_ports {en1[3]}]



set_property IOSTANDARD LVCMOS33 [get_ports {en1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {en1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {en1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {en1[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {en0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {en0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {en0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {en0[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {sseg1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg1[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {sseg0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg0[7]}]


set_property PACKAGE_PIN V15 [get_ports sram_ce_r]
set_property PACKAGE_PIN R10 [get_ports sram_lb_r]
set_property PACKAGE_PIN T16 [get_ports sram_oe_r]
set_property PACKAGE_PIN R16 [get_ports sram_ub_r]
set_property PACKAGE_PIN V16 [get_ports sram_we_r]
set_property PACKAGE_PIN U17 [get_ports {sram_data[0]}]
set_property PACKAGE_PIN U18 [get_ports {sram_data[1]}]
set_property PACKAGE_PIN U16 [get_ports {sram_data[2]}]
set_property PACKAGE_PIN V17 [get_ports {sram_data[3]}]
set_property PACKAGE_PIN T11 [get_ports {sram_data[4]}]
set_property PACKAGE_PIN U11 [get_ports {sram_data[5]}]
set_property PACKAGE_PIN U12 [get_ports {sram_data[6]}]
set_property PACKAGE_PIN V12 [get_ports {sram_data[7]}]
set_property PACKAGE_PIN V10 [get_ports {sram_data[8]}]
set_property PACKAGE_PIN V11 [get_ports {sram_data[9]}]
set_property PACKAGE_PIN U14 [get_ports {sram_data[10]}]
set_property PACKAGE_PIN V14 [get_ports {sram_data[11]}]
set_property PACKAGE_PIN T13 [get_ports {sram_data[12]}]
set_property PACKAGE_PIN U13 [get_ports {sram_data[13]}]
set_property PACKAGE_PIN T9  [get_ports {sram_data[14]}]
set_property PACKAGE_PIN T10 [get_ports {sram_data[15]}]

set_property PACKAGE_PIN T15 [get_ports {sram_addr[0]}]
set_property PACKAGE_PIN T14 [get_ports {sram_addr[1]}]
set_property PACKAGE_PIN N16 [get_ports {sram_addr[2]}]
set_property PACKAGE_PIN N15 [get_ports {sram_addr[3]}]
set_property PACKAGE_PIN M17 [get_ports {sram_addr[4]}]
set_property PACKAGE_PIN M16 [get_ports {sram_addr[5]}]
set_property PACKAGE_PIN P18 [get_ports {sram_addr[6]}]
set_property PACKAGE_PIN N17 [get_ports {sram_addr[7]}]
set_property PACKAGE_PIN P14 [get_ports {sram_addr[8]}]
set_property PACKAGE_PIN N14 [get_ports {sram_addr[9]}]
set_property PACKAGE_PIN T18 [get_ports {sram_addr[10]}]
set_property PACKAGE_PIN R18 [get_ports {sram_addr[11]}]
set_property PACKAGE_PIN M13 [get_ports {sram_addr[12]}]
set_property PACKAGE_PIN R13 [get_ports {sram_addr[13]}]
set_property PACKAGE_PIN R12 [get_ports {sram_addr[14]}]
set_property PACKAGE_PIN M18 [get_ports {sram_addr[15]}]
set_property PACKAGE_PIN L18 [get_ports {sram_addr[16]}]
set_property PACKAGE_PIN L16 [get_ports {sram_addr[17]}]
set_property PACKAGE_PIN L15 [get_ports {sram_addr[18]}]

set_property IOSTANDARD LVCMOS33 [get_ports sram_ce_r]
set_property IOSTANDARD LVCMOS33 [get_ports sram_lb_r]
set_property IOSTANDARD LVCMOS33 [get_ports sram_oe_r]
set_property IOSTANDARD LVCMOS33 [get_ports sram_ub_r]
set_property IOSTANDARD LVCMOS33 [get_ports sram_we_r]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_data[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_data[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_data[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_data[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_addr[0]}]





